# Generated by Django 2.1 on 2018-08-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtype',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'TEXT'), ('NUMBER', 'NUMBER'), ('DATE', 'DATE'), ('ENUM', 'ENUM')], max_length=32),
        ),
    ]
