# Generated by Django 2.1 on 2018-08-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_auto_20180822_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskvalue',
            name='datecreated',
            field=models.DateField(auto_now_add=True, default='2018-9-9'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskvalue',
            name='datemodified',
            field=models.DateField(auto_now_add=True, default='2018-9-9'),
            preserve_default=False,
        ),
    ]
