# Generated by Django 2.1 on 2018-08-24 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0004_auto_20180824_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldoptions',
            old_name='fields',
            new_name='fieldtype',
        ),
    ]
