# Generated by Django 2.1 on 2018-08-24 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0005_auto_20180824_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldoptions',
            name='fieldtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='risks.FieldType'),
        ),
    ]
