# Generated by Django 2.1 on 2018-08-24 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0006_auto_20180824_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('risktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.RiskType')),
            ],
        ),
        migrations.RemoveField(
            model_name='riskvalue',
            name='risktype',
        ),
        migrations.AddField(
            model_name='riskvalue',
            name='riskheader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='risks.RiskHeader'),
            preserve_default=False,
        ),
    ]
